tag latest:
  image: 
    entrypoint: [""]
    name: alpine/git
  stage: deploy
  script:
    - git --version
    - git remote remove origin
    - git remote add origin https://gitlab-ci-token:${TAGGING_TOKEN}@gitlab.com/zuru.tech/operations/devops/pre-commit-hooks
    - git tag -d latest                 
    - git push origin :refs/tags/latest  
  after_script:
    - git tag latest HEAD                
    - git push origin latest             
  only:
    - main
  retry: 1
  tags:
    - linux
    - docker
    - t0