-   id: copyright_updater
    name: Update Copyright
    description: ''
    language: python
    entry: copyright_updater
    args: ["--files"]
    additional_dependencies: []
    files: '.*\.(h|cpp|cs|py|pyi)$'
    pass_filenames: true
-   id: check_locks
    name: Check locks
    description: ''
    language: python
    entry: pre_commit
    additional_dependencies: []
    always_run: true
    pass_filenames: false
-   id: generated_header_separated
    name: Check generated header separated
    language: python
    entry: generated_header_separated
    files: '^Dreamcatcher/Source/.*\.h$'
    additional_dependencies: []